server:
  port: 8080
spring:
  application:
    name: GATEWAY
  cloud:
    discovery:
      enabled: true
    circuitbreaker:
      hystrix:
        enabled: false
eureka:
  instance:
    prefer-ip-address: true
